from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from api.contracts.common import EntityReferenceResponse
from api.contracts.entity import (
    EntityInvestigationResponse,
    EntityNetworkScoreResponse,
    RelatedEntityResponse,
)
from api.services.prediction import FEATURE_DATASET_PATH

from fraud_intelligence.intelligence.entity_investigation import (
    assemble_entity_investigation_view,
)
from fraud_intelligence.intelligence.entity_relationships import (
    EntityReference,
    build_direct_transaction_relationships,
)
from fraud_intelligence.intelligence.fraud_ring_candidates import (
    detect_fraud_ring_candidates,
)
from fraud_intelligence.intelligence.ring_network_scoring import (
    score_fraud_ring_candidates,
)


class EntityInvestigationServiceError(RuntimeError):
    """Raised when entity investigation cannot be completed."""


@dataclass(frozen=True)
class EntityInvestigationService:
    """API adapter for the frozen Phase 9 entity investigation layer."""

    feature_dataset_path: Path = FEATURE_DATASET_PATH

    def _load_dataset(self) -> pd.DataFrame:
        try:
            return pd.read_parquet(
                self.feature_dataset_path
            )
        except Exception as exc:
            raise EntityInvestigationServiceError(
                "Unable to load the feature dataset."
            ) from exc

    def _build_relationships(
        self,
        dataframe: pd.DataFrame,
    ):
        relationships = []

        required_columns = {
            "transaction_id",
            "timestamp",
        }

        missing = required_columns - set(dataframe.columns)

        if missing:
            raise EntityInvestigationServiceError(
                "Feature dataset is missing required columns: "
                + ", ".join(sorted(missing))
            )

        for _, transaction in dataframe.iterrows():
            relationships.extend(
                build_direct_transaction_relationships(
                    transaction_id=str(
                        transaction["transaction_id"]
                    ),
                    transaction_timestamp=transaction["timestamp"],
                    transaction=transaction.to_dict(),
                )
            )

        return tuple(relationships)

    def investigate(
        self,
        customer_id: str,
    ) -> EntityInvestigationResponse:
        """
        Investigate one customer using descriptive relationship context.

        No fraud prediction is generated by this service.
        """

        if not customer_id:
            raise ValueError(
                "customer_id must be non-empty."
            )

        dataframe = self._load_dataset()

        if "customer_id" not in dataframe.columns:
            raise EntityInvestigationServiceError(
                "Feature dataset does not contain customer_id."
            )

        customer_mask = (
            dataframe["customer_id"].astype(str)
            == str(customer_id)
        )

        if not customer_mask.any():
            raise KeyError(
                f"Customer {customer_id!r} was not found."
            )

        entity = EntityReference(
            entity_type="customer",
            entity_id=str(customer_id),
        )

        try:
            relationships = self._build_relationships(
                dataframe
            )

            # ------------------------------------------------------------------
            # Candidate network discovery
            #
            # Phase 9.4 is transaction-targeted, so each transaction directly
            # related to this customer is used as an investigation entry point.
            # Candidate IDs are deduplicated below.
            # ------------------------------------------------------------------

            customer_transaction_ids = tuple(
                sorted(
                    dataframe.loc[
                        customer_mask,
                        "transaction_id",
                    ]
                    .astype(str)
                    .unique()
                )
            )

            candidates_by_id = {}

            for transaction_id in customer_transaction_ids:
                result = detect_fraud_ring_candidates(
                    target_transaction_id=transaction_id,
                    relationships=relationships,
                )

                for candidate in result.candidates:
                    candidates_by_id[
                        candidate.candidate_id
                    ] = candidate

            candidates = tuple(
                sorted(
                    candidates_by_id.values(),
                    key=lambda candidate: (
                        -candidate.entity_count,
                        -candidate.relationship_count,
                        candidate.candidate_id,
                    ),
                )
            )

            network_scores = score_fraud_ring_candidates(
                candidates
            )

            investigation_view = (
                assemble_entity_investigation_view(
                    entity=entity,
                    relationships=relationships,
                    candidates=candidates,
                    network_scores=network_scores,
                )
            )

        except KeyError:
            raise
        except ValueError:
            raise
        except EntityInvestigationServiceError:
            raise
        except Exception as exc:
            raise EntityInvestigationServiceError(
                "Unable to build entity investigation."
            ) from exc

        return EntityInvestigationResponse(
            entity=EntityReferenceResponse(
                entity_type=(
                    investigation_view.entity.entity_type
                ),
                entity_id=(
                    investigation_view.entity.entity_id
                ),
            ),
            related_entities=[
                RelatedEntityResponse(
                    entity=EntityReferenceResponse(
                        entity_type=item.entity.entity_type,
                        entity_id=item.entity.entity_id,
                    ),
                    relationship_type=item.relationship_type,
                    direction=item.direction,
                    timestamp=item.timestamp,
                )
                for item in investigation_view.related_entities
            ],
            related_transactions=list(
                investigation_view.related_transactions
            ),
            candidate_ring_ids=list(
                investigation_view.candidate_ring_ids
            ),
            network_scores=[
                EntityNetworkScoreResponse(
                    candidate_id=score.candidate_id,
                    entity_count=score.entity_count,
                    relationship_count=score.relationship_count,
                    relationship_density=(
                        score.relationship_density
                    ),
                    entity_type_count=score.entity_type_count,
                    relationship_type_count=(
                        score.relationship_type_count
                    ),
                    non_transaction_entity_count=(
                        score.non_transaction_entity_count
                    ),
                    non_transaction_connectivity=(
                        score.non_transaction_connectivity
                    ),
                    structural_score=score.structural_score,
                )
                for score in investigation_view.network_scores
            ],
            investigation_summary=(
                investigation_view.investigation_summary
            ),
            temporal_rule=investigation_view.temporal_rule,
        )